name: publish to maven

on:
  push:
    tags: [v*.*.*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p ~/.gnupg
      name: gpg dir
    - run: mkdir -p ~/.sbt/1.0
      name: sbt dir
    - name: set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      
    - shell: bash
      env:
        SONASECRET: ${{ secrets.SONASECRET }}
      run: |
        echo "$SONASECRET" > ~/.sbt/1.0/sonatype.sbt 

    - shell: bash
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: |
        echo -n "$GPG_KEY" | base64 --decode | gpg --import
        
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: build and publish
      run: sbt test publishSigned sonatypeBundleRelease